/* eslint-disable @next/next/no-page-custom-font */
import Providers from "../redux/Provider";
import "@/styles/globals.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Ezpics",
  description: "Generated by create next app",
  icons: {
    icon: "/images/ezlogo",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body suppressHydrationWarning={true} className="font-poppins">
        <Providers>
          {children}
          <ToastContainer theme="colored" />
        </Providers>
      </body>
    </html>
  );
}
