import Header from "@/components/Header";
import Nav from "@/components/Nav";
import "@/styles/home/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <header>
          <Header />
        </header>
        <main className="flex pt-[--header-height]">
          <nav className="">
            <Nav />
          </nav>
          <div className="content">{children}</div>
        </main>
      </body>
    </html>
  );
}
